/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/layout.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon.vue')['default']
  }
}
